config/routes.rb
Rails.application.routes.draw do
  resources :shelters do
    resources :pets, only: %i[show new create]
  end
  get "shelters/:id/dashboard", to: "shelters#dashboard", as: "shelter_dashboard"
  resources :pets, except: %i[create new]
  # post "pets", to: "pets#create", as: "create_pet"
  devise_for :users
  root to: "pages#home"
  resources :pets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "pages/profile", to: "pages#profile"
  resources :pets do
    collection do
      get :all
    end
    resources :appointments, only: %i[create destroy]
    resources :favorites, only: [:create]
    get 'new_favorite', to: 'pets#new_favorite', as: 'new_favorite'
  end
  resources :favorites, only: [:index]
end

app/models/shelter.rb
class Shelter < ApplicationRecord
  belongs_to :user
  has_many :pets, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :description, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_shelter, only: %I[show destroy edit update dashboard]

  def index
    @shelters = policy_scope(Shelter).all
    @markers = @shelters.geocoded.map do |shelter|
      {
        lat: shelter.latitude,
        lng: shelter.longitude,
        info: render_to_string(partial: "pages/popup", locals: { shelter: shelter }),
        marker_html: render_to_string(partial: "pages/marker")
      }
    end
  end

  def show
    authorize @shelter
  end

  def new
    @shelter = Shelter.new
    authorize @shelter
  end

  def create
    @shelter = Shelter.new(shelter_params)
    @shelter.user = current_user
    authorize @shelter
    if @shelter.save
      redirect_to shelter_path(@shelter)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @shelter
  end

  def update
    authorize @shelter
    if @shelter.update(shelter_params)
      redirect_to shelter_path(@shelter)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @shelter
    @shelter.destroy
    redirect_to shelters_path, status: :see_other
  end

  def dashboard
    authorize @shelter
    @pets = Pet.where(shelter: @shelter)
    @appointments = []
    @pets.each do |pett|
      if Appointment.where(pet: pett).present?
        @appointments += Appointment.where(pet: pett).to_a
      end
    end

    @reviews = []
    @appointments.each do |appoint|
      if Review.where(appointment: appoint).present?
        @reviews = Review.where(appointment: appoint).to_a
      end
    end
  end

  private

  def set_shelter
    @shelter = Shelter.find(params[:id])
  end

  def shelter_params
    params.require(:shelter).permit(:name, :phone_number, :description, :address)
  end
end

app/views/shelters/_pet_card.html.erb
<div class="pet-index">
  <div class="create-pet-btn" style="background-color: white">
    <div class="create-pet-btn-img">
      <%= image_tag "pets_comp6.png", alt: "", width:"100%" %>
    </div>
    <div class="create-btn">
      <%= button_to "Create New Pet", new_shelter_pet_path(@shelter), method: :get, class: "create-new-btn" %>
    </div>
  </div>
  <% @pets.each do |pet| %>
    <div class="dashboard-pet-index-card">
      <div class="dashboard-pet-index-avatar">
        <%= cl_image_tag pet.photo.key, width: 85, class: "dashboard-pet-index-avatar" %>
      </div>
      <div class="dashboard-pet-index-info">
        <div class="dashboard-pet-info overflow-hidden">
          <h5 class="wrap-line white-letter-header"><%= pet.name %></h5>
          <h6 class="wrap-line white-letter-text"> <%= pet.gender %> · <%= pet.age %> · <%= pet.breed %></h6>
        </div>
        <div class="edit-btn">
          <%= button_to "Edit", edit_pet_path(pet), method: :get, class: "pet-edit-btn" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shelters/dashboard.html.erb
<div class="dashboard-container padding-top-pages">
  <div class="shelter-info">
    <div class="shelter-photo">
      <%= cl_image_tag @shelter.photo.key, class: "border-img" %>
    </div>
    <div class="shelter-general">
      <div class="general-info">
        <h1 class="margin-shrink white-letter wrap-line"><%= @shelter.name %></h1>
        <div class="adress-phone">
          <p class="remove-margin-bottom white-letter wrap-line overflow-hidden">Address: <%= @shelter.address %></p>
          <p class="white-letter">Phone: <%= @shelter.phone_number %></p>
        </div>
        <div class="working-hour">
          <h5 class="white-letter hours">Working Hours:</h5>
          <div class="flex-hour">
            <div>
              <p class="remove-margin-bottom white-letter">Monday</p>
              <p class="remove-margin-bottom white-letter">Tuesday</p>
              <p class="remove-margin-bottom white-letter">Wednesday</p>
              <p class="remove-margin-bottom white-letter">Thrusday</p>
              <p class="remove-margin-bottom white-letter">Friday</p>
            </div>
            <div class="time-margin">
              <p class="remove-margin-bottom white-letter">9am - 6pm</p>
              <p class="remove-margin-bottom white-letter">9am - 6pm</p>
              <p class="remove-margin-bottom white-letter">9am - 4pm</p>
              <p class="remove-margin-bottom white-letter">9am - 4pm</p>
              <p class="remove-margin-bottom white-letter">9am - 8pm</p>
            </div>
          </div>
        </div>
      </div>
      <div class="info-photo">
        <div class="edit-shelter-btn">
          <%= button_to "Edit Profile", edit_shelter_path(@shelter), method: :get, class: "polish-button" %>
        </div>
        <div class="info-photo-flex">
          <%= image_tag "pets_comp7.png", alt: "", width:"100%" %>
        </div>
      </div>
    </div>
  </div>
  <div class="shelter-description-dashboard">
    <div class="description">
      <h4 class="white-letter dashboard-header">Description</h4>
      <p class="white-letter text-evenly"><%= @shelter.description %></p>
    </div>
    <div class="description-right">
      <div class="pet-count">
        <div>
          <h4 class="white-letter count">Cats</h4>
          <h4 class="white-letter count"><%= @pets.where(species: "cat").count %></h4>
        </div>
        <div>
          <h4 class="white-letter count">Dogs</h4>
          <h4 class="white-letter count"><%= @pets.where(species: "dog").count %></h4>
        </div>
        <div>
          <h4 class="white-letter count">Adopted</h4>
          <h4 class="white-letter count"><%= @pets.where(status: "adopted").count %></h4>
        </div>
      </div>
      <div class="description-photo">
        <%= image_tag "pets_comp5.png", alt: "", width:"60%" %>
      </div>
    </div>
  </div>
  <div class="pets-of-shelter">
    <div class="">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="all-tab" data-bs-toggle="tab" data-bs-target="#all" type="button" role="tab" aria-controls="all" aria-selected="true">All</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="catall-tab" data-bs-toggle="tab" data-bs-target="#cats" type="button" role="tab" aria-controls="cats" aria-selected="false">Cats</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="dogall-tab" data-bs-toggle="tab" data-bs-target="#dogs" type="button" role="tab" aria-controls="dogs" aria-selected="false">Dogs</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="other-tab" data-bs-toggle="tab" data-bs-target="#other" type="button" role="tab" aria-controls="other" aria-selected="false">Others</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="adopted-tab" data-bs-toggle="tab" data-bs-target="#adopted" type="button" role="tab" aria-controls="adopted" aria-selected="false">Adopted</button>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active pet-index-container" id="all" role="tabpanel" aria-labelledby="all-tab">
          <%= render "pet_card" %>
        </div>
        <div class="tab-pane fade pet-index-container" id="cats" role="tabpanel" aria-labelledby="catall-tab">
          <% cats = @pets.where(species: "cat") %>
          <% if cats.empty? %>
            <h4 calss="text-center">This shelter has no cat yet.</h4>
          <% else %>
            <div class="pet-index">
              <% cats.each do |cat| %>
                <div class="dashboard-pet-index-card">
                  <div class="dashboard-pet-index-avatar">
                    <%= cl_image_tag cat.photo.key, width: 85, class: "dashboard-pet-index-avatar" %>
                  </div>
                  <div class="dashboard-pet-index-info">
                    <div class="dashboard-pet-info overflow-hidden">
                      <h5 class="wrap-line white-letter"><%= cat.name %></h5>
                      <h6 class="wrap-line white-letter"> <%= cat.gender %> · <%= cat.age %> · <%= cat.breed %></h6>
                    </div>
                    <div class="edit-btn">
                      <%= button_to "Edit", edit_pet_path(cat), method: :get, class: "pet-edit-btn" %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="tab-pane fade pet-index-container" id="dogs" role="tabpanel" aria-labelledby="dogall-tab">
          <% dogs = @pets.where(species: "dog") %>
          <% if dogs.empty? %>
            <h4 calss="text-center">This shelter has no dog yet.</h4>
          <% else %>
            <div class="pet-index">
              <% dogs.each do |dog| %>
                <div class="dashboard-pet-index-card">
                  <div class="dashboard-pet-index-avatar">
                    <%= cl_image_tag dog.photo.key, width: 85, class: "dashboard-pet-index-avatar" %>
                  </div>
                  <div class="dashboard-pet-index-info">
                    <div class="dashboard-pet-info overflow-hidden">
                      <h5 class="wrap-line white-letter"><%= dog.name %></h5>
                      <h6 class="wrap-line white-letter"> <%= dog.gender %> · <%= dog.age %> · <%= dog.breed %></h6>
                    </div>
                    <div class="edit-btn">
                      <%= button_to "Edit", edit_pet_path(dog), method: :get, class: "pet-edit-btn" %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="tab-pane fade pet-index-container" id="other" role="tabpanel" aria-labelledby="other-tab">
          <% others = @pets.where.not(species: ['cat', 'dog']) %>
          <% if others.empty? %>
            <h4 calss="text-center">Oops...</h4>
          <% else %>
            <div class="pet-index">
              <% others.each do |other| %>
                <div class="dashboard-pet-index-card">
                  <div class="dashboard-pet-index-avatar">
                    <%= cl_image_tag other.photo.key, width: 85, class: "dashboard-pet-index-avatar" %>
                  </div>
                  <div class="dashboard-pet-index-info">
                    <div class="dashboard-pet-info overflow-hidden">
                      <h5 class="wrap-line white-letter"><%= other.name %></h5>
                      <h6 class="wrap-line white-letter"> <%= other.gender %> · <%= other.age %> · <%= other.breed %></h6>
                    </div>
                    <div class="edit-btn">
                      <%= button_to "Edit", edit_pet_path(other), method: :get, class: "pet-edit-btn" %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="tab-pane fade pet-index-container" id="adopted" role="tabpanel" aria-labelledby="adopted-tab">
          <% adopted = @pets.where(status: "adopted") %>
          <% if adopted.empty? %>
            <h4 class="text-center">Waiting for adoption...</h4>
          <% else %>
            <div class="pet-index">
              <% adopted.each do |adopt| %>
                <div class="dashboard-pet-index-card">
                  <div class="dashboard-pet-index-avatar">
                    <%= cl_image_tag adopt.photo.key, width: 85, class: "dashboard-pet-index-avatar" %>
                  </div>
                  <div class="dashboard-pet-index-info">
                    <div class="dashboard-pet-info overflow-hidden">
                      <h5 class="wrap-line white-letter"><%= adopt.name %></h5>
                      <h6 class="wrap-line white-letter"> <%= adopt.gender %> · <%= adopt.age %> · <%= adopt.breed %></h6>
                    </div>
                    <div class="edit-btn">
                      <%= button_to "Edit", edit_pet_path(adopt), method: :get, class: "pet-edit-btn" %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="appointment-request">
    <h4 class="white-letter dashboard-header">Appointment Requests</h4>
    <% if @appointments.empty? %>
      <div class="appointment-card-empty">
        <h1 class="white-letter empty">Oops...You have no upcoming appointment yet.</h1>
      </div>
    <% else %>
      <div class="appointment-request-group">
        <% @appointments.each do |appointment| %>
          <% pet = Pet.find_by(id: appointment.pet_id) %>
          <div class="appointment-request-card">
            <div class="appointment-card-info">
              <div class="appointment-card-date">
                <h5 class="white-letter"><%= appointment.date %></h6>
                <h5 class="white-letter">Pet:  <%= pet.name %></h6>
              </div>
              <div class="appointment-card-time">
                <h5 class="white-letter">Time:  <%= appointment.time.strftime("%H:%M") %></h5>
              </div>
            </div>
            <%# <div class="appointment-card-btn">
              <button class="accept-btn">Accept</button>
              <button class="decline-btn">Decline</button>
            </div> %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="shelter-review">
    <h4 class="white-letter dashboard-header">Reviews</h4>
    <% if @reviews.empty? %>
      <div class="review-empty">
        <h1 class="white-letter empty">Oops...This shelter have no review yet.</h1>
      </div>
    <% else %>
      <div class="review-list">
        <% @reviews.each do |review| %>
          <% review_user = User.find_by(id: review.user_id) %>
          <div class="review-card">
            <div class="review-photo">
              <%= cl_image_tag review_user.photo.key, width: 100, height: 100, class: "review-avatar" %>
            </div>
            <div class="review-content">
              <h5 class="white-letter"><%= review.title %></h5>
              <p class="white-letter text-evenly"><%= review.comment %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shelters/edit.html.erb
<div class="new-form-container padding-top-pages">
  <div class="new-pet-head">
    <%= image_tag "pets_comp2.png", alt: "", width:"70%" %>
  </div>
  <h1 class="headline">Edit Profile of <%= @shelter.name %></h1>

  <div class="new-pet-form">
    <%= simple_form_for @shelter, html: { class: 'create-new-pet-form' } do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="new-pet-form-top">
        <div class="form-inputs">
          <%= f.input :name %>
        </div>

        <div class="form-inputs">
          <%= f.input :phone_number %>
        </div>

        <div class="form-inputs">
          <%= f.input :address %>
        </div>

        <div class="form-inputs">
          <%= f.input :photo, as: :file, label: "Image of Shelter" %>
        </div>
      </div>

      <div class="new-pet-form-bottom">
        <div class="form-inputs">
          <%= f.input :description, as: :text, input_html: { style: 'height: 125px;' } %>
        </div>

        <div class="form-actions mb-2">
          <%= f.button :submit, class: "create-new-pet-form-btn" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shelters/index.html.erb
<div class="container-shelters pt-5">

  <div class="row mt-3 justify-content-between">
    <div class="col-6 row p-0 pt-3">
      <% @shelters.each do |shelter| %>
        <% if shelter.photo.attached? %>
          <div class="col-6 mb-3">
            <div class="card shelter-view-card">
              <div class="shelter-view-card shelter_image">
                <%= link_to(shelter) do %>
                <%= cl_image_tag shelter.photo.key, width: 100, class: "shelter_image" %>
                <% end %>
                <div class="card-body shelter-view-info">
                  <div class="w-100">
                    <h4 class="shelters-card-header"><%= shelter.name %></h4>
                    <p class="card-text-white-text">📍<%= shelter.address %></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-6 sticky-map p-0">
      <div data-controller="map"
        id='map'
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        data-map-markers-value="<%= @markers.to_json %>"
        style='width: 100%; height: 87vh;'>
      </div>
    </div>
  </div>
</div>

app/views/shelters/new.html.erb
<div class="new-form-container padding-top-pages">
  <div class="new-pet-head">
    <%= image_tag "pets_comp2.png", alt: "", width:"70%" %>
  </div>
  <h1 class="headline">New Shelter</h1>

  <div class="new-pet-form">
    <%= simple_form_for @shelter, html: { class: 'create-new-pet-form' } do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="new-pet-form-top">
        <div class="form-inputs">
          <%= f.input :name, placeholder: 'Name', label: false %>
        </div>

        <div class="form-inputs">
          <%= f.input :phone_number, placeholder: 'Phone number', label: false %>
        </div>

        <div class="form-inputs">
          <%= f.input :address, placeholder: 'Adress', label: false %>
        </div>

        <div class="form-inputs">
          <%= f.input :photo, as: :file, placeholder: 'Photo', label: false %>
        </div>
      </div>

      <div class="new-pet-form-bottom">
        <div class="form-inputs">
          <%= f.input :description, as: :text, input_html: { style: 'height: 125px;' } %>
        </div>

        <div class="form-actions mb-2">
          <%= f.button :submit, class: "create-new-pet-form-btn" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shelters/show.html.erb
<div class="shelter_container padding-top-pages">
  <div class="bread-crumbs">
    <div class="user-btn">
      <a href="/shelters"  role="button">← Back</a>
    </div>
    <div class="user-btn">
      <a href="/shelters" role="button">Next →</a>
    </div>
  </div>
  <div class="shelter_show_info">
<!-- Image -->
    <div class="shelter_show_img">
      <%=  cl_image_tag @shelter.photo.key, class: "shelter_avatar" %>
    </div>
<!-- Shelter Info -->
   <div class="shelter-show-general">
      <div class="shelter-show-info">
        <h1 class="shelter-name-text"><%= @shelter.name %></h1>
          <div class="owner-btn-shelter">
          <% if policy(@shelter).destroy? %>
            <%= link_to 'Delete',
            shelter_path(@shelter),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          <% end %>
          <% if policy(@shelter).edit? %>
            <%= link_to 'Edit this shelter', edit_shelter_path(@shelter) %>
          <% end %>
        </div>
        <div class="shelter-texts">


        <p class="shelter-details"><script src="https://cdn.lordicon.com/ritcuqlt.js"></script>
          <lord-icon
              src="https://cdn.lordicon.com/etqbfrgp.json"
              trigger="hover"
              colors="outline:#131432,primary:#d4d1fa,secondary:#a39cf4,tertiary:#b26836,quaternary:#ebe6ef"
              style="width:25px;height:25px;margin-bottom:-8px;margin-left: -4px;">
          </lord-icon> <span class="shelter-detail-text"> <%= @shelter.address %></span></p><br>


          <p class="shelter-details"><script src="https://cdn.lordicon.com/ritcuqlt.js"></script>
            <lord-icon
                src="https://cdn.lordicon.com/bjnaomnr.json"
                trigger="hover"
                colors="outline:#121331,primary:#e5d1fa,secondary:#3a3347,tertiary:#2ea28b"
                style="width:35px;height:35px;margin-bottom:-8px;margin-left: -9px;margin-right: -4px;">
            </lord-icon>
          <span class="shelter-detail-text"> <%= @shelter.phone_number %></span></p><br>


        <div class="working-hour-margin-shelter">
          <h5 class="description-shelter-text"><strong>Working Hours:</strong></h5>
          <div class="flex-hour">
            <div>
              <p class="description-shelter-text">Monday</p>
              <p class="description-shelter-text">Tuesday</p>
              <p class="description-shelter-text">Wednesday</p>
              <p class="description-shelter-text">Thrusday</p>
              <p class="description-shelter-text">Friday</p>
            </div>
            <div class="time-margin">
              <p class="description-shelter-text">9am - 6pm</p>
              <p class="description-shelter-text">9am - 6pm</p>
              <p class="description-shelter-text">9am - 4pm</p>
              <p class="description-shelter-text">9am - 4pm</p>
              <p class="description-shelter-text">9am - 8pm</p>
                      </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
 <!-- Shelter Description -->
  <div class="shelter-description">
    <div class="description-text">
      <h4 class="shelter-description-header">Hello, nice to meet you <script src="https://cdn.lordicon.com/ritcuqlt.js"></script>
  <lord-icon
      src="https://cdn.lordicon.com/lzwckydi.json"
      trigger="hover"
      colors="primary:#ebe6ef,secondary:#121331,tertiary:#d1e3fa,quaternary:#7166ee,quinary:#f49cc8"
      style="width:60px;height:60px;margin-bottom:-13px; margin-left:-18px">
  </lord-icon> </h4>
<br>
      <p class="shelter-description-paragraph"><%= @shelter.description %></p>
    </div>
<!-- Image -->
    <div class="shelter-description-right">
      <%= image_tag "pets_comp4.png", alt: "", width:"100%" %>
    </div>
  </div>
  <div class="">
    <h4 class="pets-description-header">Our Pets</h4>
  </div>
<div class="">
  </div>
  <div class="container-pets-home">
    <div class="row row-cols-1 row-cols-md-4 g-4">
      <% @shelter.pets.each do |pet| %>
        <% if pet.photo.attached? %>
          <div class="col">
            <div class="card pets-view-card">
              <div class="pets-view-card pet_image">
                <%= link_to(pet) do %>
                <%= cl_image_tag pet.photo.key, width: 100, class: "pet_image" %>
              </div>
                <a href="<%= "/pets/#{pet.id}" %>" class="discover-more-link">
                  <div class="card-body pet-view-info">
                    <div class="left-block">
                      <h5 class="pets-card-header"><%= pet.name %></h5>
                      <h6 class="card-text white-text"> <%= pet.breed %></h6>
                      <h6 class="card-text white-text"> <%= pet.gender %> · <%= pet.age %> years old</h6>
                    </div>
                  </div>
                </a>
            </div>
          </div>
           <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  </div>
  <br>
  <br>
  <br>
</div>