config/routes.rb
Rails.application.routes.draw do
  resources :shelters do
    resources :pets, only: %i[show new create]
  end
  get "shelters/:id/dashboard", to: "shelters#dashboard", as: "shelter_dashboard"
  resources :pets, except: %i[create new]
  # post "pets", to: "pets#create", as: "create_pet"
  devise_for :users
  root to: "pages#home"
  resources :pets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "pages/profile", to: "pages#profile"
  resources :pets do
    collection do
      get :all
    end
    resources :appointments, only: %i[create destroy]
    resources :favorites, only: [:create]
    get 'new_favorite', to: 'pets#new_favorite', as: 'new_favorite'
  end
  resources :favorites, only: [:index]
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :shelter
  has_many :appointments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user
  has_one_attached :photo

  validates :name, presence: true
  validates :species, presence: true
  validates :breed, presence: true
  validates :gender, presence: true
  validates :description, presence: true
  validates :age, presence: true
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_pet, only: %I[show destroy edit update]
  before_action :set_shelter, only: %I[new create]

  def index
    @pets = policy_scope(Pet)
    if params[:species].present?
      @pets = @pets.where(species: params[:species])
    end
    if params[:gender].present?
      @pets = @pets.where(gender: params[:gender])
    end
    if params[:age_from].present? && params[:age_to].present?
      @pets = @pets.where(age: params[:age_from]..params[:age_to])
    end
    if params[:location].present?
      # location accept country name for now
      @pets = @pets.select do |pet|
        Geocoder.search([pet.shelter.latitude, pet.shelter.longitude]).first.country == params[:location]
      end
    end
  end

  def new_favorite
    @pet = Pet.find(params[:pet_id])
    @favorite = @pet.favorites.new
    authorize @favorite
  end

  def show
    authorize @pet
    # @shelters = policy_scope(Shelter).all
    @shelter = @pet.shelter
    # @markers = @shelter.geocoded.map do |shelters|
    #   {
    #     lat: shelters.latitude,
    #     lng: shelters.longitude,
    #     info: render_to_string(partial: "pages/popup", locals: { shelter: shelters }),
    #     marker_html: render_to_string(partial: "pages/marker")
    #   }
    # end
    @markers = [
      lat: @shelter.latitude,
      lng: @shelter.longitude,
      info: render_to_string(partial: "pages/popup", locals: { shelter: @shelter }),
      marker_html: render_to_string(partial: "pages/marker")
    ]
  end

  def new
    @pet = Pet.new
    authorize @pet
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.shelter = @shelter
    authorize @pet
    if @pet.save
      redirect_to shelter_dashboard_path(@shelter), notice: 'Pet was successfully created.'
    else
      flash[:alert] = 'Unable to create pet.Be sure to fill in all fields.'
      redirect_to shelter_dashboard_path(@shelter), status: :unprocessable_entity
    end
  end

  def edit
    authorize @pet
  end

  def update
    authorize @pet
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @pet
    @pet.destroy
    redirect_to pets_path, status: :see_other
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :age, :description, :photo, :species, :breed, :gender, :status)
  end

  def set_shelter
    @shelter = Shelter.find(params[:shelter_id])
  end
end

app/views/pets/edit.html.erb
<div class="new-form-container padding-top-pages">
  <div class="new-pet-head">
    <%= image_tag "pets_comp2.png", alt: "", width:"70%" %>
  </div>
  <h1 class="headline">Edit Profile of <%= @pet.name %></h1>

  <div class="new-pet-form">
  <%= simple_form_for @pet, html: { class: 'create-new-pet-form' } do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="new-pet-form-top">
      <div class="form-inputs">
        <%= f.input :name %>
      </div>

      <div class="form-inputs">
        <%= f.input :species %>
      </div>

      <div class="form-inputs">
        <%= f.input :breed %>
      </div>

      <div class="form-inputs">
        <%= f.input :gender %>
      </div>

      <div class="form-inputs">
        <%= f.input :age %>
      </div>

      <div class="form-inputs">
        <%= f.input :status, collection: ["not adopted", "adopted"] %>
      </div>

      <div class="form-inputs">
        <%= f.input :photo, as: :file, label: "Image of Pet" %>
      </div>
    </div>

    <div class="new-pet-form-bottom">
      <div class="form-inputs">
        <%= f.input :description, as: :text, input_html: { style: 'height: 125px;' } %>
      </div>

      <div class="form-actions mb-2">
        <%= f.button :submit, class: "create-new-pet-form-btn" %>
      </div>
    </div>
  <% end %>
</div>

</div>

app/views/pets/index.html.erb
<div class="banner padding-top-pages" style="background-color: #9787FD;">
  <div class="search-bar-container">
    <h1 class="pet-index-headline-search">Start Your Search Now</h1>
    <div class="center-container">
      <div class="card-search">
      <div class="search-bar">
        <form action="/pets" method="get" class="form-inline">
          <div class="form-group">
            <select name="location" id="location" class="form-select form-control border-radius input-lg">
              <option value="">Location</option>
              <option value="France">France</option>
              <option value="Germany">Germany</option>
              <option value="Poland">Poland</option>
              <option value="Hungary">Hungary</option>
              <option value="Latvia">Latvia</option>
              <option value="Romania">Romania</option>
              <option value="Slovenia">Slovenia</option>
            </select>
          </div>
          <div class="form-group">
            <select name="species" id="species" class="form-select form-control border-radius input-lg">
              <option value="">Pet Type</option>
              <% @pet_types.each do |type| %>
              <option value= <%= type %> ><%= type.capitalize %></option>
              <% end %>
            </select>
          </div>
          <div class="form-group">
            <select name="gender" id="gender" class="form-select form-control border-radius input-lg">
              <option value="">Gender</option>
              <option value="male">Male</option>
              <option value="female">Female</option>
            </select>
          </div>

          <div class="form-group">
            <input type="number" name="age" id="age" min="1" class="form-select form-control border-radius input-lg" placeholder="Age">
          </div>
          <div class="form-group">
            <button type="submit" class="btn-home">Search</button>
          </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-pets">
  <div class="row row-cols-1 row-cols-md-4 g-4 mt-3">
    <% @pets.each do |pet| %>
      <% if pet.photo.attached? %>
        <div class="col">
          <div class="card pets-view-card">
            <div class="pets-view-card pet_image">
              <%= link_to(pet) do %>
              <%= cl_image_tag pet.photo.key, width: 100, class: "pet_image" %>
            </div>
              <a href="<%= "/pets/#{pet.id}" %>" class="discover-more-link">
                <div class="card-body pet-view-info">
                  <div class="left-block">
                    <h5 class="pets-card-header"><%= pet.name %></h5>
                    <h6 class="card-text white-text"> <%= pet.breed %></h6>
                    <h6 class="card-text white-text"> <%= pet.gender %> · <%= pet.age %> years old</h6>
                  </div>
                <div class="pet-details">
                  <h6 class="shelter-top right-align-text">Located at</h6>
                  <div class="shelter-container">
                    <div class="shelter-content">
                      <h5 class="shelter right-align-text"><%= pet.shelter.name %></h5>
                    </div>
                  </div>
                </div>
                </div>
              </a>
          </div>
        </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pets/new.html.erb
<div class="new-form-container padding-top-pages">
  <div class="new-pet-head">
    <%= image_tag "pets_comp2.png", alt: "", width:"70%" %>
  </div>
  <h1 class="headline">New Pet</h1>
  <div class="new-pet-form">
    <%= simple_form_for [@shelter, @pet], html: { class: 'create-new-pet-form' } do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="new-pet-form-top">
        <div class="form-inputs">
          <%= f.input :name, placeholder: 'Name', label: false %>
        </div>

        <div class="form-inputs">
          <%= f.input :species, placeholder: 'Species', label: false %>
        </div>

        <div class="form-inputs">
          <%= f.input :breed, placeholder: 'Breed', label: false %>
        </div>

        <div class="form-inputs">
          <%= f.input :gender, collection: ['Female', 'Male'], prompt: 'Select a gender', placeholder: '', label: false %>
        </div>

        <div class="form-inputs">
          <%= f.input :age, placeholder: 'Age', label: false %>
        </div>

        <div class="form-inputs">
          <%= f.input :photo, as: :file, placeholder: 'Photo', label: false %>
        </div>
      </div>

      <div class="new-pet-form-bottom">
        <div class="form-inputs">
          <%= f.input :description, as: :text, input_html: { style: 'height: 125px;' }, placeholder: 'Description', label: false %>
        </div>

        <div class="form-actions mb-2">
          <%= f.button :submit, class: "create-new-pet-form-btn" %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/pets/show.html.erb
<div class="pet_container padding-top-pages">
  <div class="bread-crumbs">
    <div class="user-btn">
      <a href="/pets"  role="button">← Back</a>
    </div>
    <div class="user-btn">
      <a href="/pets" role="button">Next →</a>
    </div>
  </div>
  <div class="pet_show_info">
  <!-- Image -->
    <div class="pet_show_img">
      <%= cl_image_tag @pet.photo.key, class: "pet_avatar" %>
    </div>
    <!-- Pet Info -->
    <div class="pet-show-general">
      <div class="pet-show-info">
        <h1 class="pet-name-text"><%= @pet.name %></h1>
          <div class="owner-btn">
          <% if policy(@pet).destroy? %>
            <%= link_to 'Delete',
            pet_path(@pet),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          <% end %>
          <% if policy(@pet).edit? %>
            <%= link_to 'Edit this pet', edit_pet_path(@pet) %>
          <% end %>
        </div>
        <div class="pet-texts">
          <p class="pet-details">Age: <span class="pet-detail-text"><%= @pet.age %> years old</span></p><br>
          <p class="pet-details">Breed: <span class="pet-detail-text"><%= @pet.breed %></span></p><br>
          <p class="pet-details">Gender: <span class="pet-detail-text"><%= @pet.gender %></span></p><br>
          <p class="pet-details">Status: <span class="pet-detail-text"><%= @pet.status %></span></p><br>
        </div>
        <script src="https://cdn.lordicon.com/ritcuqlt.js"></script>
      </div>

      <%# BUTTON FOR APPOINTMENTS %>

        <% if Appointment.find_by(pet: @pet, user: current_user).present? %>
          <div class="cancel-btn">
            <%= button_to 'Cancel Appointment', pet_appointment_path(@pet.id), method: :delete, class: "btn btn-cancel" %>
          </div>
        <% else %>
      <div class="appointment-card">
        <form action=<%= "/pets/#{@pet.id}/appointments" %> method="post" class="d-flex align-items-center justify-content-between">
        <div class="mb-3">
          <label for="appointmentdate" class="form-label">Pick A Date</label>
          <input type="date" class="form-control py-3" id="appointmentdate" name="appointmentdate" >
        </div>
        <div class="mb-3">
          <label for="appointmenttime" class="form-label">Pick A Time</label>
          <input type="time" class="form-control py-3" id="appointmenttime" name="appointmenttime">
        </div>
        <button type="submit" class="btn btn-appointment">Create Appointment</button>
      </form>
      </div>
        <% end %>
    </div>
  </div>

<!-- Pet Description -->
  <div class="pet-description">
    <div class="description-text">
      <h4 class="pet-description-header">About <%= @pet.name %></h4>
      <p class="pet-description-paragraph"><%= @pet.description %></p>
    </div>
    <!-- Image -->
    <div class="pet-description-right">
      <%= image_tag "pets_comp5.png", alt: "", width:"80%" %>
    </div>
  </div>

  <!-- Shelter -->
  <div class="pet_show_info-map">
    <div class="pet-show-general-left">
      <h1 class="shelter-description-header"><%= @pet.shelter.name %></h1>
      <p class="description-shelter-text"><script src="https://cdn.lordicon.com/ritcuqlt.js"></script>
          <lord-icon
              src="https://cdn.lordicon.com/etqbfrgp.json"
              trigger="hover"
              colors="outline:#131432,primary:#d4d1fa,secondary:#a39cf4,tertiary:#b26836,quaternary:#ebe6ef"
              style="width:25px;height:25px;margin-bottom:-8px;margin-left: -4px;">
          </lord-icon> <%= @pet.shelter.address %></p>
      <p class="description-shelter-text"><script src="https://cdn.lordicon.com/ritcuqlt.js"></script>
            <lord-icon
                src="https://cdn.lordicon.com/bjnaomnr.json"
                trigger="hover"
                colors="outline:#121331,primary:#e5d1fa,secondary:#3a3347,tertiary:#2ea28b"
                style="width:35px;height:35px;margin-bottom:-8px;margin-left: -9px;margin-right: -4px;">
            </lord-icon> <%= @pet.shelter.phone_number %></p>
      <div class="working-hour margin">
          <h5 class="description-shelter-text"><strong>Working Hours:</strong></h5>
          <div class="flex-hour">
            <div>
              <p class="description-shelter-text">Monday</p>
              <p class="description-shelter-text">Tuesday</p>
              <p class="description-shelter-text">Wednesday</p>
              <p class="description-shelter-text">Thrusday</p>
              <p class="description-shelter-text">Friday</p>
            </div>
            <div class="time-margin">
              <p class="description-shelter-text">9am - 6pm</p>
              <p class="description-shelter-text">9am - 6pm</p>
              <p class="description-shelter-text">9am - 4pm</p>
              <p class="description-shelter-text">9am - 4pm</p>
              <p class="description-shelter-text">9am - 8pm</p>
            </div>
          </div>
        </div>
    </div>
    <!-- MAP -->
    <div class="pet-show-general-right">
      <div data-controller="map"
        id='pet-map'
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        data-map-markers-value="<%= @markers.to_json %>"
        style='width: 100%; height: 300px; border-radius: 15px;'>
      </div>
    </div>
  </div>
</div>