config/routes.rb
Rails.application.routes.draw do
  resources :shelters do
    resources :pets, only: %i[show new create]
  end
  get "shelters/:id/dashboard", to: "shelters#dashboard", as: "shelter_dashboard"
  resources :pets, except: %i[create new]
  # post "pets", to: "pets#create", as: "create_pet"
  devise_for :users
  root to: "pages#home"
  resources :pets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "pages/profile", to: "pages#profile"
  resources :pets do
    collection do
      get :all
    end
    resources :appointments, only: %i[create destroy]
    resources :favorites, only: [:create]
    get 'new_favorite', to: 'pets#new_favorite', as: 'new_favorite'
  end
  resources :favorites, only: [:index]
end

app/views/pages/_marker.html.erb
<%= image_tag "marker-cat.png", height: 30, width: 30, alt: "Cat" %>

app/views/pages/_popup.html.erb
<h1><%= shelter.name %></h1>
<p><%= shelter.address %></p>

app/views/pages/home.html.erb
<div class="banner padding-top-pages" style="background-color: #9787FD;">
  <div class="container-top">
    <h1 class="headline-top"><span data-controller="typed-js"></span></h1>
    <div class="center-container">
      <p class= "tag_line">Paws: discover the perfect pet match through our extensive network of trusted shelters.</p>
    </div>
    <div class="center-container">
      <%= image_tag "pets_comp2.png", alt: "", width:"100%", class: "top_image"%>
    </div>
    <div class="center-container">
      <%= link_to "SEE ALL", "/pets", class: "btn btn-flat" %>
    </div>
  </div>
</div>


<div class="container_home">

  <div class="home-content-wrap">
    <div class="lilac-card" style="background-color: #9787FD;">
      <div class="image-container">
        <%= image_tag "pets_comp3.png", alt: "" %>
      </div>
    </div>
    <div class="text-container">
      <h2 class="subhead">About Us</h2>
      <p class="home-text">At Paws, our mission is to forge enduring bonds between pets in need and caring families throughout Europe. We recognize the significance of discovering an ideal companion, and our devoted team is committed to guiding you through the pet adoption process with ease and assurance.</p>
      <p class="home-text">Our platform links you to an extensive network of reputable shelters and pet owners, providing a diverse selection of carefully chosen pets that align with your preferences, lifestyle, and living space. We firmly believe that every pet is deserving of a loving and nurturing home.</p>
      <p class="home-text">As a trusted partner in your pet adoption journey, we strive to ensure a seamless experience by offering personalized support and a wealth of resources. Together, we can help make a difference in the lives of countless pets and families, creating a brighter future for all.</p>
    </div>
  </div>
</div>


<div class="banner" style="background-color: #9787FD;">
  <div class="search-bar-container">
    <div class="center-container">
      <%= image_tag "pets_comp8.png", alt: "", width:"100%", class: "search_image"%>
    </div>
    <h1 class="headline_search">Start Your Search Now</h1>
    <div class="center-container">
      <div class="card-search">
      <div class="search-bar">
        <form action="/pets" method="get" class="form-inline">
          <div class="form-group">
            <select name="location" id="location" class="form-select form-control border-radius input-lg">
              <option value="">Location</option>
              <option value="France">France</option>
              <option value="Germany">Germany</option>
              <option value="Poland">Poland</option>
              <option value="Hungary">Hungary</option>
              <option value="Latvia">Latvia</option>
              <option value="Romania">Romania</option>
              <option value="Slovenia">Slovenia</option>
              <option value="Switzerland">Switzerland</option>
            </select>
          </div>
          <div class="form-group">
            <select name="species" id="species" class="form-select form-control border-radius input-lg">
              <option value="">Pet Type</option>
              <% @pet_types.each do |type| %>
              <option value= <%= type %> ><%= type.capitalize %></option>
              <% end %>
            </select>
          </div>
          <div class="form-group">
            <select name="gender" id="gender" class="form-select form-control border-radius input-lg">
              <option value="">Gender</option>
              <option value="male">Male</option>
              <option value="female">Female</option>
            </select>
          </div>

          <div class="form-group">
            <input type="number" name="age" id="age" min="1" class="form-control border-radius input-lg padding-search" placeholder="Age">
          </div>
          <div class="form-group">
            <button type="submit" class="btn-home">Search</button>
          </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Pets -->
<div class="container_home">
  <div class="home-content-no-margin">
    <div class="text-container mt-5">
      <h2 class="subhead">Our Pets</h2>
    </div>
    <div class="see-container">
      <p class="see_more">See More</p>
    </div>
  </div>
  <div class="container-pets-home">
    <div class="row row-cols-1 row-cols-md-4 g-4">
      <% @random_pets.each do |pet| %>
        <% if pet.photo.attached? %>
          <div class="col">
            <div class="card pets-view-card">
              <div class="pets-view-card pet_image">
                <%= cl_image_tag pet.photo.key, width: 100, class: "pet_image" %>
              </div>
                <a href="<%= "/pets/#{pet.id}" %>" class="discover-more-link">
                  <div class="card-body pet-view-info">
                    <div class="left-block">
                      <h5 class="pets-card-header"><%= pet.name %></h5>
                      <h6 class="card-text white-text"> <%= pet.breed %></h6>
                      <h6 class="card-text white-text"> <%= pet.gender %> · <%= pet.age %> years old</h6>
                    </div>
                  <div class="pet-details">
                    <h6 class="shelter-top right-align-text">Located at</h6>
                    <div class="shelter-container">
                      <div class="shelter-content">
                        <h5 class="shelter right-align-text"><%= pet.shelter.name %></h5>
                      </div>
                    </div>
                  </div>
                  </div>
                </a>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <!-- Events -->
  <div class="home-content-wrap">
    <div class="lilac-card" style="background-color: #9787FD;">
      <div class="image-container mt-1">
        <%= image_tag "pets_comp7.png", alt: "", style: "width: 98%;" %>
      </div>
    </div>
    <div class="text-container">
      <h2 class="subhead">Events</h2>
      <p class="home-text">Join us at our adoption events and take the first step towards creating a lifelong bond with your perfect pet match. Our heartwarming events showcase a diverse array of lovable pets from trusted shelters, making it easy for you to meet and interact with your potential new companion in a friendly and supportive environment. We believe that every pet deserves a loving and nurturing home, and our goal is to connect you with the perfect pet that aligns with your preferences and lifestyle.</p>
      <p class="home-text">We understand that finding the right pet can be a challenging and overwhelming process, which is why our adoption events are designed to make the experience as enjoyable and stress-free as possible. Our events are held regularly at various locations throughout Europe, and our team is dedicated to ensuring that each event is a fun and memorable experience for both you and the pets.</p>
    </div>
  </div>
  <!-- Map -->
  <div data-controller="map"
    id='map'
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
    data-map-markers-value="<%= @markers.to_json %>"
    style='width: 100%; height: 300px;'>
  </div>
<!-- Shelters -->
  <div class="home-content-no-margin mt-4">
    <div class="text-container">
      <h2 class="subhead">Shelters</h2>
    </div>
    <div class="see-container">
      <p class="see_more">See More</p>
    </div>
  </div>
  <div class="container-shelters-home">
  <div class="row row-cols-1 row-cols-md-4 g-4 mb-5">
  <% @shelters.sample(8).each do |shelter| %>
    <% if shelter.photo.attached? %>
      <div class="col">
        <div class="card shelter-view-card">
          <div class="shelter-view-card shelter_image">
            <%= link_to(shelter) do %>
            <%= cl_image_tag shelter.photo.key, width: 100, class: "shelter_image" %>
            <% end %>
            <div class="card-body shelter-view-info">
              <div class="w-100">
                <h4 class="shelters-card-header"><%= shelter.name %></h4>
                <p class="card-text-white-text">📍<%= shelter.address %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
  </div>
  </div>
<!-- Video -->
  <div class="video-content-wrap">
    <div class="ai-container">
      <iframe src="https://app.movio.la/embeds/1f793c788758417c84cfef680e5c75b3"
      title="Movio video player"  allow="encrypted-media; fullscreen;" allowfullscreen width="100%" height= "500" style= "border: none" style= "align: middle"></iframe>
    </div>
    <div class="video-text-container">
      <h2 class="subhead">Recommendations</h2>
      <p class="home-text">We are incredibly proud of the positive difference we have made in the lives of over 2000 animals across Europe since our launch in early 2023. Our team at Paw has been part of the journey for each and every adoption, and we couldn't be happier that these animals have found forever homes. </p>
      <p class="home-text">We are grateful for the love and care they have been provided, and it truly warms our hearts to know that we have played a part in it. We hope that more and more animals will be able to find loving homes in the future.</p>
      <p class="home-text">Maybe you provide a new home?</p>
    </div>
  </div>
</div>
<!-- Reasons-->
<!--
<div class="banner" style="background-color: #9787FD;">
  <div class="home-content-wrap-banner">
    <div class="text-container">
      <h2 class="subhead-white">Reasons to Adopt</h2>
      <p class="home-subhead-white">💜 Save a Life</p>
      <p class="home-text-white">By adopting a pet from a shelter, you are giving a deserving animal a second chance at life. Many shelters are overcrowded, and adoption can help make room for other animals in need.</p>
      <p class="home-subhead-white">💜 Combat Pet Overpopulation</p>
      <p class="home-text-white">Adopting a pet helps reduce the number of animals in shelters, which can become overwhelmed due to pet overpopulation.</p>
      <p class="home-subhead-white">💜 Reduce Overbreeding</p>
      <p class="home-text-white">Taking a pet from a shelter helps combat overbreeding and discourages irresponsible breeding practices. Many unscrupulous breeders contribute to pet overpopulation and unhealthy animals.</p>

    </div>
    <div class="lilac-card" style="background-color: #9787FD;">
      <div class="image-container mt-1">
        <%= image_tag "pets_comp4.png", alt: "", style: "width: 100%;" %>
      </div>
    </div>
  </div>
</div> -->

app/views/pages/profile.html.erb
<div class="profile-container padding-top-pages">
  <div class="profile-banner">
    <div class="profile-left">
      <div class="profile-img">
        <%= cl_image_tag current_user.photo.key, width: 150, height: 150, class: "round-avatar" %>
      </div>
      <%# <div class="user-info"> %>
        <div class="user-info">
          <h1 class="white-letter spacing"><%= current_user.email %></h1>
          <h5 class="small-info white-letter profile-subhead">Berlin, Germany</h5>
          <p class="white-letter user-description">Looking to adopt a dog to provide they with companionship and encourage they to get outside and be more active.</p>
        </div>
        <%# <button class="user-edit-btn">Edit profile</button> %>
      </div>
    <%# </div> %>
    <div class="profile-right">
      <%= image_tag "pets_comp9.png", alt: "", width:"95%" %>
    </div>
  </div>
  <div class="profile-appointment">
    <h4 class="white-letter profile-header">Appointments</h4>
    <% if @appointments.empty? %>
      <div class="profile-appointment-empty">
        <h1 class="white-letter empty">Go get your first appointment</h1>
      </div>
    <% else %>
      <div class="profile-appointment-info">
        <% @appointments.each do |appointment| %>
          <% pet = Pet.find_by(id: appointment.pet_id) %>
          <a href=<%= "/pets/#{pet.id}" %> class="profile-appointment-card">
            <div class="profile-appointment-avatar">
              <%= cl_image_tag pet.photo.key, width: 75, height: 75, class: "pet-avatar" %>
            </div>
            <div class="profile-appointment-date">
              <div>
                <h6><%= appointment.date %></h6>
              </div>
              <div>
                <h6></h6>Pet: <%= pet.name %></h6>
              </div>
            </div>
            <div class="profile-appointment-time">
              <h6>Time: <%= appointment.time.strftime("%H:%M") %></h6>
            </div>
          </a>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="profile-shelter-favourites">
    <% if @shelters.empty? %>
      <div class="profile-shelter-empty">
        <div class="d-flex justify-content-between">
          <h4 class="white-letter profile-header">My Shelters</h4>
          <%= button_to "Create Shelter", new_shelter_path, method: :get, class: "create-shelter-list-btn" %>
        </div>
        <div class="profile-create-shelter">
          <h5 class="white-letter empty">You haven't created a shelter yet</h5>
        </div>
      </div>
    <% else %>
      <div class="profile-shelter-list">
        <div class="d-flex justify-content-between">
          <h4 class="white-letter profile-header">My Shelters</h4>
          <%= button_to "Create Shelter", new_shelter_path, method: :get, class: "create-shelter-list-btn" %>
        </div>
        <div class="profile-shelter-link">
          <ul class="list-dot">
            <% @shelters.each do |shelter| %>
              <li class="equal-size"><a href=<%= "/shelters/#{shelter.id}/dashboard" %> class="list-decoration"><%= shelter.name %></a></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    <% if @favorites.empty? %>
      <div class="profile-favorites-empty">
        <h4 class="white-letter profile-header">My Favorites</h4>
        <div class="favorite-empty-sign">
          <h1 class="white-letter empty">You haven't liked any pet yet</h1>
        </div>
      </div>
    <% else %>
      <div class="profile-pet-list">
        <h4 class="white-letter profile-header">My Favorite Pets</h4>
          <div class="profile-pet-link">
          <ul class="list-dot">
            <% @favorites.each do |favorite| %>
              <% pet = Pet.find_by(id: favorite.pet_id) %>
              <li class="equal-size"><a href=<%= "/pets/#{pet.id}" %> class="list-decoration"><%= pet.name %></a></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>